application: x2-serious-case-3
version: 4
runtime: python27
threadsafe: false
api_version: 1

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: main.py
